### ISSUE TITLE
Schedule: Mobile View - If there is only one day, enable expand all with one click on menu already

### ISSUE THREAD

**Issue by mariobehling** [OpenTechSummit/2016.opentechsummit.net#45]
Currently in mobile view, the script add a "menu" link on the right. In order to expand the tracks of each day, it is necessary to click two times (a. on the menu icon and b. on the date - 5th May). This feature is correct if there are several days of an event. If there is only one day, there is no reason why two clicks should be required. Please change the script accordingly:
If there is only one day - enable the expansion of the menu and submenu on one click on the menu icon.

**Comment by championswimmer** [comment]
Further explanation

Step 0 ![screenshot from 2016-05-01 20 35 31](https://cloud.githubusercontent.com/assets/1327050/14942519/a842b266-0fdc-11e6-8b4a-9ae899034134.png)

Step 1 ![screenshot from 2016-05-01 20 35 37](https://cloud.githubusercontent.com/assets/1327050/14942518/a83f3dfc-0fdc-11e6-9b1b-e5fe48ab6869.png)

Step 2![screenshot from 2016-05-01 20 35 43](https://cloud.githubusercontent.com/assets/1327050/14942520/a84a4a6c-0fdc-11e6-853e-6c0b013d9f6f.png)

Go from Step0 to Step2 in one click, instead of 2 clicks, if there is only one day
